// generated from madeira_history.html — timeline eras
class Era {
  final String years, titleEn, titlePt, img, bodyEn, bodyPt;
  const Era(this.years, this.titleEn, this.titlePt, this.img, this.bodyEn, this.bodyPt);
}

const eras = <Era>[
  Era('1419 – 1500s', 'Clearing a vertical island', 'Arrotear uma ilha vertical', 'history/1821-rural-occupations.jpg', 'When Zarco\'s caravels reached the island in 1419, it was one dense laurel forest — madeira means “wood”. Settlers burned and cleared, then did something remarkable: instead of giving up on slopes too steep to plough, they carved them into thousands of tiny stone-walled terraces, the poios. Every basket of soil and every harvest travelled on someone\'s back, up and down paths that today\'s runners know as race courses.', 'Quando as caravelas de Zarco chegaram em 1419, a ilha era uma floresta Laurissilva cerrada — daí o nome Madeira. Os povoadores queimaram e arrotearam, e fizeram algo notável: em vez de desistir das encostas íngremes demais para arar, talharam-nas em milhares de socalcos murados, os poios. Cada cesto de terra e cada colheita viajou às costas de alguém, por veredas que os corredores de hoje conhecem como percursos de prova.'),
  Era('1450 – 1600', 'White gold — sugar cane', 'Ouro branco — a cana-de-açúcar', 'history/1900-sugar-cane-harvest.jpg', 'By the mid-1400s Madeira was Europe\'s first great sugar island. Cane from Sicily loved the warm south coast, water-driven engenhos crushed it, and Funchal sugar reached Flanders and Venice — for a while the island produced most of the sugar sold in Western Europe. Christopher Columbus came here as a sugar buyer and married into a settler family on Porto Santo. Sugar built Funchal\'s first churches and its first fortunes, before Brazil\'s plantations undercut it a century later.', 'Em meados de Quatrocentos a Madeira era a primeira grande ilha do açúcar da Europa. A cana da Sicília deu-se bem na costa sul, os engenhos de água moíam-na, e o açúcar do Funchal chegava à Flandres e a Veneza — durante décadas a ilha produziu a maior parte do açúcar vendido na Europa ocidental. Cristóvão Colombo veio cá como comprador de açúcar e casou com uma família povoadora do Porto Santo. O açúcar ergueu as primeiras igrejas e fortunas do Funchal, até as plantações do Brasil o baterem no preço um século depois.'),
  Era('1600 – 1900', 'Wine carried on shoulders', 'Vinho levado aos ombros', 'history/1828-wine-carriers.jpg', 'After sugar came the vine. Madeira wine crossed every ocean — heated and rocked in ships\' holds, it only got better, and it was raised in toasts to American independence in 1776. On the island itself every drop moved by muscle: the borracheiros carried ~40-litre goatskins of wine on their shoulders from mountain vineyards down to the Funchal lodges, walking distances that would count as a respectable trail race today.', 'Depois do açúcar veio a vinha. O vinho Madeira cruzou todos os oceanos — aquecido e embalado nos porões, só melhorava, e brindou-se com ele a independência americana em 1776. Na ilha, cada gota movia-se a músculo: os borracheiros desciam das vinhas até aos armazéns do Funchal com borrachos de ~40 litros ao ombro, percorrendo distâncias que hoje dariam uma boa prova de trail.'),
  Era('1461 – today', 'Levadas — water walking on cliffs', 'Levadas — água a caminhar nas arribas', 'history/1890-levada-path.jpg', 'Rain falls on the north side of Madeira; the sun and the farms are on the south. The answer, started in the 1460s and still growing five centuries later, was the levadas: over 3,000 km of hand-cut water channels that contour the island through cliffs and tunnels. Builders — the rocheiros — worked hanging from wicker baskets on ropes over the void. Beside every channel runs the narrow path the levadeiro walked daily to keep the water flowing. Those maintenance paths are exactly what you hike today: the levada trails are a 550-year-old workplace.', 'A chuva cai no norte da Madeira; o sol e as fazendas estão no sul. A resposta, começada na década de 1460 e ainda a crescer cinco séculos depois, foram as levadas: mais de 3 000 km de canais talhados à mão, contornando arribas e furando túneis. Os rocheiros trabalhavam pendurados em cestos de vime sobre o abismo. Ao lado de cada canal corre a vereda estreita que o levadeiro percorria todos os dias. São essas veredas de serviço que hoje se caminham: os trilhos das levadas são um local de trabalho com 550 anos.'),
  Era('1600s – 1930s', 'Moving without wheels', 'Mover-se sem rodas', 'history/1821-hammock-travel.jpg', 'Until the 20th century Madeira had almost no roads a wheel could use — everything was too steep. People and goods moved by hammock slung on two carriers\' shoulders, by ox-drawn runner sledges on the polished basalt streets, and, from about 1850, by the famous Monte toboggan: a wicker basket on wooden runners, steered downhill at speed by two carreiros in straw hats. Hemingway called it one of the most exhilarating rides of his life. It still runs every day — the world\'s oldest downhill ride.', 'Até ao século XX a Madeira quase não tinha estradas para rodas — tudo era íngreme demais. Pessoas e cargas moviam-se de rede ao ombro de dois carregadores, em corsas puxadas a bois sobre o basalto polido e, desde cerca de 1850, no famoso carro do Monte: um cesto de vime sobre patins de madeira, guiado a alta velocidade por dois carreiros de chapéu de palha. Hemingway chamou-lhe uma das descidas mais emocionantes da sua vida. Ainda desce todos os dias — o transporte de descida mais antigo do mundo.'),
  Era('1900s – 1970s', 'Bananas take the terraces', 'A banana toma os socalcos', 'history/1900-banana-carrier-bp166.jpg', 'The 20th century belonged to the banana. The warm coastal poios below 300 m turned into a green staircase of plantations, and bananas — small, sweet, silver-skinned — became the south coast\'s cash crop, shipped to Lisbon by the boatload. The photo above captures a turning point: in 1961 a banana field at Santa Catarina was cleared for the new airport, the moment subsistence-farming Madeira started becoming the trail-tourism Madeira of today.', 'O século XX foi da banana. Os poios quentes abaixo dos 300 m tornaram-se uma escadaria verde de fazendas, e a banana da Madeira — pequena, doce — passou a ser a cultura de exportação da costa sul, embarcada para Lisboa. A foto acima capta uma viragem: em 1961 um campo de bananeiras em Santa Catarina foi arroteado para o novo aeroporto — o momento em que a Madeira agrícola começou a tornar-se a Madeira do trail e do turismo de hoje.'),
];