// generated from madeira_history.html — album captions EN + PT
class RootsItem {
  final String year, caption, captionPt, img;
  const RootsItem(this.year, this.caption, this.captionPt, this.img);
}

const rootsItems = <RootsItem>[
  RootsItem('1547', 'A pilot climbs the mainmast of a four-master to take the height of the sun with a cross-staff, sea monsters curling in the waves below — coloured woodcut printed at Funchal\'s latitude, 1547. Public domain.', 'Um piloto trepa ao mastro grande de uma nau de quatro mastros para medir a altura do sol com a balestilha, monstros marinhos nas ondas — xilogravura colorida, 1547. Domínio público.', '1547-astrolabe-funchal.jpg'),
  RootsItem('1693', 'How the world saw Madeira in 1693 — Vincenzo Coronelli, cosmographer of the Venetian Republic, engraved the island with its rhumb lines, the Canaries below, and a little panorama of Funchal from the sea. You can stand in front of this very map at the Banana Museum in Funchal. Arquivo Regional da Madeira, CC BY-SA 4.0.', 'Como o mundo via a Madeira em 1693 — Vincenzo Coronelli, cosmógrafo da República de Veneza, gravou a ilha com as suas linhas de rumo, as Canárias em baixo e um pequeno panorama do Funchal visto do mar. Este mapa pode ver-se ao vivo no Museu da Banana, no Funchal. Arquivo Regional da Madeira, CC BY-SA 4.0.', '1693-coronelli-map.jpg'),
  RootsItem('1821', 'Three women at their daily chores outside a stone cottage among young banana plants: one kneads in a wicker basin, the old woman in the middle spins wool with a drop spindle — a cat asleep on her lap — and the third grinds grain at a small hand mill. Hand-coloured plate from “A History of Madeira”, London, 1821. Public domain.', 'Três mulheres nas lidas diárias junto a uma casa de pedra, entre bananeiras novas: uma amassa numa gamela de vime, a velhinha ao centro fia lã com um fuso — um gato ao colo — e a terceira mói grão num moinho de mão. Gravura aguarelada de “A History of Madeira”, Londres, 1821. Domínio público.', '1821-rural-occupations.jpg'),
  RootsItem('1821', 'A lady reclines in a fringed hammock slung from a single pole, two barefoot carriers at either end; behind, a gentleman follows on horseback while his groom trots alongside holding the horse\'s tail uphill. Plate, 1821. Public domain.', 'Uma senhora recostada numa rede franjada, pendurada num só pau, com dois carregadores descalços; atrás, um cavalheiro a cavalo, com o arrieiro agarrado à cauda na subida. Gravura, 1821. Domínio público.', '1821-hammock-travel.jpg'),
  RootsItem('1828', 'No wheels, no problem: a wine cask lashed to a wooden runner-sledge (corsa) and dragged by a yoke of oxen, one driver walking ahead with the goad, another steadying the barrel. Wood engraving, 1828. Public domain.', 'Sem rodas, sem problema: um casco de vinho amarrado a uma corsa de madeira, puxado por uma junta de bois — um homem à frente com a aguilhada, outro a segurar o barril. Xilogravura, 1828. Domínio público.', '1828-wine-carriers.jpg'),
  RootsItem('1890', '“Lavada road” — a walled water-lane above Funchal, quintas and cypresses on the ridge, two carriers with a shoulder pole in the middle of the road. Albumen photograph, 1890s, Rijksmuseum collection. Public domain.', '“Lavada road” — um caminho murado sobre o Funchal, quintas e ciprestes no cimo, dois carregadores com um pau ao ombro no meio da estrada. Fotografia em albumina, anos 1890, coleção do Rijksmuseum. Domínio público.', '1890-levada-path.jpg'),
  RootsItem('1900', 'Sunday at the Monte Palace Hotel lake — a rowing party on the water, a fountain, a folly tower on the rocks and gentlemen in hats on the garden benches; Funchal postage stamps of 1905 on the corner. Tinted postcard. Public domain.', 'Domingo no lago do Monte Palace Hotel — um passeio de barco, o repuxo, a torre-miradouro sobre as rochas e senhores de chapéu nos bancos do jardim; selos do Funchal de 1905 ao canto. Postal colorido. Domínio público.', '1900-monte-palace-gardens.jpg'),
  RootsItem('1900', 'A file of borracheiros under the vine pergola at Cossart Gordon & Co. — each man with a full goatskin of young wine on his shoulders and a walking staff, the lodge\'s great casks waiting on the right. Tinted postcard, c. 1900. Public domain.', 'Fila de borracheiros sob a latada nos armazéns da Cossart Gordon & Co. — cada homem com um borracho cheio de vinho ao ombro e o seu bordão, os cascos grandes à espera, à direita. Postal colorido, c. 1900. Domínio público.', '1900-borracheiros-cossart.jpg'),
  RootsItem('1900', '“Sugar-cane cutting” — a whole family in the cane field, long canes over shoulders, the cut bundles packed into woven baskets for the walk to the mill; a quinta watches from the hill. Postcard, c. 1900. Public domain.', '“Apanha de canas” — uma família inteira no canavial, canas ao ombro, os molhos atados em cestos de vime para a caminhada até ao engenho; uma quinta espreita do alto. Postal, c. 1900. Domínio público.', '1900-sugar-cane-harvest.jpg'),
  RootsItem('1900', 'Two carreiros in whites and red sashes haul their wicker sledge back up the polished, rutted lane past the gates of Reid\'s Mount Park Hotel, ready for the next run down. Postcard, c. 1900. Public domain.', 'Dois carreiros de branco e faixa vermelha puxam o carro de cesto pela calçada polida, junto ao portão do Reid\'s Mount Park Hotel, prontos para a próxima descida. Postal, c. 1900. Domínio público.', '1900-monte-toboggan.jpg'),
  RootsItem('1900', 'The banana on the move, c. 1900 — a carrier in linen and borracheiro boots, a whole branch slung from his shoulder pole, posing dead-serious in the studio. Bazar do Povo postcard no. 166, “Madeira, Costumes” — on display at the Banana Museum in Funchal. Public domain.', 'A banana a caminho, c. 1900 — um carregador de linho e botas de borracheiro, o cacho inteiro pendurado do pau ao ombro, a posar seriíssimo no estúdio. Postal do Bazar do Povo n.º 166, «Madeira, Costumes» — em exposição no Museu da Banana, no Funchal. Domínio público.', '1900-banana-carrier-bp166.jpg'),
  RootsItem('1910', 'The Monte rack railway, c. 1910 — a steam plume rises at the mid-slope station while the twin towers of the Monte church watch from the hilltop. Postcard. Public domain.', 'O comboio do Monte, c. 1910 — um penacho de vapor sobe na estação a meia encosta, com as torres da igreja do Monte lá no alto. Postal. Domínio público.', '1910-monte-railway.jpg'),
  RootsItem('1955', 'The Short Solent flying boat City of Funchal of Aquila Airways on the water, 1950s — for a decade the only way to fly to Madeira was to land on the sea. Photo: RuthAS, CC BY 3.0.', 'O hidroavião Short Solent City of Funchal da Aquila Airways na água, anos 1950 — durante uma década, voar para a Madeira era amarar na baía. Foto: RuthAS, CC BY 3.0.', '1955-aquila-flying-boat.jpg'),
  RootsItem('1960', 'The brick chimney of the Torreão (Hinton) sugar factory towering over Funchal\'s rooftops like a lighthouse of industry, c. 1960 — cane was still being milled in the middle of the city within living memory. ABM. Public domain.', 'A chaminé de tijolo da fábrica do Torreão (Hinton) por cima dos telhados do Funchal, c. 1960 — ainda se moía cana no meio da cidade em memória viva. ABM. Domínio público.', '1960-torreao-sugar-factory.jpg'),
  RootsItem('1961', 'A bulldozer noses through the banana grove while officials in suits look on from beside a thatched palheiro — first day of demolition for Funchal\'s airfield, 5 June 1961. Photo: Atelier Vicente\'s, Madeira Photography Museum / ABM. Public domain.', 'Um bulldozer rasga o bananal sob o olhar de senhores de fato, junto a um palheiro de colmo — primeiro dia das demolições para o aeródromo do Funchal, 5 de junho de 1961. Foto: Atelier Vicente\'s, Museu de Fotografia da Madeira / ABM. Domínio público.', '1961-banana-field-airport.jpg'),
  RootsItem('2010', 'Atlantic Festival pyromusical over the bay — every June Saturday the fireworks tradition that made Funchal\'s New Year a world record gets a rehearsal. Photo: Michael Gaylard, CC BY 2.0.', 'Piromusical do Festival do Atlântico sobre a baía — todos os sábados de junho ensaia-se a tradição que fez da passagem de ano do Funchal um recorde mundial. Foto: Michael Gaylard, CC BY 2.0.', '2010-atlantic-fireworks.jpg'),
  RootsItem('2012', 'A baker in the traditional carapuça cap turns bolo do caco rounds on the hot plate of a bamboo festa stall — the sweet-potato flatbread was originally baked on a shard (caco) of basalt. Photo: Stephen Colebourne, CC BY 2.0.', 'Um padeiro de carapuça vira bolos do caco na chapa de uma banca de festa em bambu — o pão de batata-doce cozia-se originalmente sobre um caco de basalto. Foto: Stephen Colebourne, CC BY 2.0.', '2012-bolo-do-caco.jpg'),
  RootsItem('2012', 'An arraial after dark in Santo António — strings of bulbs, paper garlands, and on the left the fire where the espetada skewers glow. This is where the island\'s kitchen lives. Photo: PESP / Wikimedia, CC BY-SA 3.0.', 'Arraial noturno em Santo António — lâmpadas em fio, grinaldas de papel e, à esquerda, o fogo onde as espetadas brilham. É aqui que mora a cozinha da ilha. Foto: PESP / Wikimedia, CC BY-SA 3.0.', '2012-arraial.jpg'),
  RootsItem('2019', 'Festa da Flor, 2019 — a “sea” of thousands of hydrangeas with real fishing boats afloat in it, bananas in the bow. The whole city becomes a stage set every spring. Photo: Bookhound~commonswiki, CC BY-SA 4.0.', 'Festa da Flor, 2019 — um «mar» de milhares de hortênsias com barcos de pesca verdadeiros a boiar nele, bananas à proa. Todas as primaveras a cidade inteira vira cenário. Foto: Bookhound~commonswiki, CC BY-SA 4.0.', '2019-festa-da-flor.jpg'),
];