// generated from madeira_history.html — island stories
class Chapter {
  final String years, titleEn, titlePt, img, capEn, capPt, bodyEn, bodyPt;
  const Chapter(this.years, this.titleEn, this.titlePt, this.img, this.capEn, this.capPt, this.bodyEn, this.bodyPt);
}

class Story {
  final String emoji, years, titleEn, titlePt;
  final List<Chapter> chapters;
  const Story(this.emoji, this.years, this.titleEn, this.titlePt, this.chapters);
}

const stories = <Story>[
  Story('🥾', '1461 – today', 'Levadas — water walking on cliffs', 'Levadas — água a caminhar nas arribas', [
    Chapter('', '', '', 'levada-25fontes-modern.jpg', 'A levada today — the water still runs in its hand-cut channel and the maintenance path beside it is now one of the world\'s loveliest walks. Here the Levada das 25 Fontes contours the green Rabaçal valley. Photo CC BY-SA 3.0.', 'Uma levada hoje — a água ainda corre no canal talhado à mão e a vereda ao seu lado é hoje um dos passeios mais bonitos do mundo. Aqui, a Levada das 25 Fontes contorna o verde vale do Rabaçal. Foto CC BY-SA 3.0.', 'Rain falls on the north side of Madeira; the sun and the farms are on the south. The answer, started in the 1460s and still growing five centuries later, was the levadas: over 3,000 km of hand-cut water channels that contour the island through cliffs and tunnels. Builders — the rocheiros — worked hanging from wicker baskets on ropes over the void. Beside every channel runs the narrow path the levadeiro walked daily to keep the water flowing. Those maintenance paths are exactly what you hike today: the levada trails are a 550-year-old workplace.', 'A chuva cai no norte da Madeira; o sol e as fazendas estão no sul. A resposta, começada na década de 1460 e ainda a crescer cinco séculos depois, foram as levadas: mais de 3 000 km de canais talhados à mão, contornando arribas e furando túneis. Os rocheiros trabalhavam pendurados em cestos de vime sobre o abismo. Ao lado de cada canal corre a vereda estreita que o levadeiro percorria todos os dias. São essas veredas de serviço que hoje se caminham: os trilhos das levadas são um local de trabalho com 550 anos.'),
  ]),
  Story('⛵', '1419 – 1964', 'Transport — sails to wings', 'Transportes — da vela às asas', [
    Chapter('1419 – 1600s', 'Caravels, Columbus & corsairs', 'Caravelas, Colombo e corsários', '1547-astrolabe-funchal.jpg', 'A pilot climbs the mainmast of a four-master to take the height of the sun with a cross-staff, sea monsters curling in the waves below — coloured woodcut printed at Funchal\'s latitude, 1547. Public domain.', 'Um piloto trepa ao mastro grande de uma nau de quatro mastros para medir a altura do sol com a balestilha, monstros marinhos nas ondas — xilogravura colorida, 1547. Domínio público.', 'Madeira sat on the great sailing highway: catch the trade winds south past the island and the Atlantic carries you to Africa, India or Brazil. Every fleet of the Age of Discovery — Magellan\'s generation included — watched Madeira\'s peaks rise and sink on the horizon. Columbus did more than pass: he came in the 1470s as a sugar buyer, married Filipa Moniz, daughter of Porto Santo\'s first captain, and lived on the little golden island where his son Diego was born. His house still stands there. Wealth attracted sharper visitors. In 1566 the French corsair Bertrand de Montluc landed a thousand men, sacked Funchal for a fortnight and stripped its churches. The crown\'s answer was stone: the São Tiago fortress and the seafront batteries you still walk past on the marina promenade.', 'A Madeira ficava na grande autoestrada da vela: apanhados os alísios a sul da ilha, o Atlântico levava-o a África, à Índia ou ao Brasil. Todas as frotas dos Descobrimentos — a geração de Magalhães incluída — viram os picos da Madeira erguer-se e afundar-se no horizonte. Colombo fez mais do que passar: veio nos anos 1470 comprar açúcar, casou com Filipa Moniz, filha do primeiro capitão do Porto Santo, e viveu na ilha dourada, onde nasceu o filho Diego. A casa ainda lá está. A riqueza atraiu visitas mais afiadas. Em 1566 o corsário francês Bertrand de Montluc desembarcou mil homens e saqueou o Funchal durante duas semanas. A resposta da coroa foi em pedra: a fortaleza de São Tiago e as baterias da frente-mar por onde ainda hoje se passeia.'),
    Chapter('1893 – 1964', 'Rails, wheels & wings', 'Carris, rodas e asas', '1910-monte-railway.jpg', 'The Monte rack railway, c. 1910 — a steam plume rises at the mid-slope station while the twin towers of the Monte church watch from the hilltop. Postcard. Public domain.', 'O comboio do Monte, c. 1910 — um penacho de vapor sobe na estação a meia encosta, com as torres da igreja do Monte lá no alto. Postal. Domínio público.', 'For 450 years nothing on Madeira rolled — everything slid, swung or walked. Then came a burst of machines. In 1893 a rack-and-pinion railway began climbing from Funchal to Monte, steam pushing carriages 550 m up the hillside; a boiler explosion in 1919 broke the public\'s trust, and the last train ran in 1943 — today\'s cable car follows almost the same line. The island\'s first automobile arrived in 1904, to streets built for sledge runners. Aviation came by sea: from 1949 to 1958 the flying boats of Aquila Airways left Southampton and splashed down in Funchal bay, passengers rowed ashore like in the age of sail. Only in 1964 did the island get a runway — carved out of a banana field at Santa Catarina. From caravel to jet: 545 years.', 'Durante 450 anos nada rolou na Madeira — tudo deslizava, balançava ou ia a pé. Depois vieram as máquinas de rajada. Em 1893 um comboio de cremalheira começou a subir do Funchal ao Monte, 550 m de encosta a vapor; a explosão de uma caldeira em 1919 quebrou a confiança, e o último comboio partiu em 1943 — o teleférico de hoje segue quase a mesma linha. O primeiro automóvel chegou em 1904, a ruas feitas para patins de corsa. A aviação chegou pelo mar: de 1949 a 1958 os hidroaviões da Aquila Airways largavam de Southampton e amaravam na baía do Funchal, com os passageiros levados a terra a remos, como no tempo da vela. Só em 1964 a ilha ganhou uma pista — rasgada num bananal em Santa Catarina. Da caravela ao jato: 545 anos.'),
  ]),
  Story('🌺', '1800s – today', 'Flora — flowers & bananas', 'Flora — flores e bananas', [
    Chapter('1800s – today', 'Flowers off the ships', 'Flores vindas dos navios', '1900-monte-palace-gardens.jpg', 'Sunday at the Monte Palace Hotel lake — a rowing party on the water, a fountain, a folly tower on the rocks and gentlemen in hats on the garden benches; Funchal postage stamps of 1905 on the corner. Tinted postcard. Public domain.', 'Domingo no lago do Monte Palace Hotel — um passeio de barco, o repuxo, a torre-miradouro sobre as rochas e senhores de chapéu nos bancos do jardim; selos do Funchal de 1905 ao canto. Postal colorido. Domínio público.', 'Every ship that watered at Funchal left something growing. Captains, botanists and the English wine families filled their quintas with trophies of the whole Empire\'s routes: strelitzias from South Africa, jacarandás and orchids from Brazil, proteas, camellias from Japan, agapanthus that now line every levada in June. On an island with no frost, nothing ever asked to leave. The hobby became an identity. The gardens of Monte and Palheiro turned into pilgrimage sites, agapanthus and hydrangeas escaped the gardens and colonised the roadsides — and each spring the whole collection parades down Funchal\'s avenue as the Festa da Flor. And the most travelled plant of all is in the timeline below: the banana, which climbed off the ships in the 19th century, took over the warm coastal poios and ended up giving its field to the airport runway.', 'Cada navio que fazia aguada no Funchal deixava algo a crescer. Capitães, botânicos e as famílias inglesas do vinho encheram as suas quintas com troféus de todas as rotas: estrelícias da África do Sul, jacarandás e orquídeas do Brasil, proteas, camélias do Japão, agapantos que hoje bordam todas as levadas em junho. Numa ilha sem geada, nada pediu para voltar. O passatempo virou identidade. Os jardins do Monte e do Palheiro tornaram-se lugares de romaria, os agapantos e as hortênsias fugiram dos jardins para as bermas — e cada primavera a coleção inteira desfila pela avenida do Funchal na Festa da Flor. E a planta mais viajada de todas está na linha do tempo, mais abaixo: a banana, que saiu dos navios no séc. XIX, tomou os poios quentes da costa e acabou por dar o seu campo à pista do aeroporto.'),
  ]),
  Story('🎉', '1419 – today', 'An island that never stops celebrating', 'Uma ilha que nunca pára de festejar', [
    Chapter('', '', '', '2010-atlantic-fireworks.jpg', 'Fireworks over the amphitheatre bay — the Atlantic Festival\'s June pyromusical, a rehearsal for the record-breaking New Year that crowns the island\'s year of festas. Photo: Michael Gaylard, CC BY 2.0.', 'Fogo sobre a baía-anfiteatro — o piromusical de junho do Festival do Atlântico, ensaio para a passagem de ano recordista que coroa o ano de festas da ilha. Foto: Michael Gaylard, CC BY 2.0.', 'The festa is Madeira\'s oldest social technology. In a land of scattered cliff-side parishes, the arraial — saint\'s day, harvest thanksgiving and village reunion rolled into one — was the moment everyone walked over the mountain to meet: streets carpeted in flowers and laurel, wine straight from the cask, espetada smoking on laurel skewers, the bailinho danced till the levada path home caught the sunrise. The pilgrimages to Monte, Ponta Delgada and Machico moved thousands on foot long before anyone called it hiking. The wine trade added gunpowder — fireworks over the amphitheatre bay became Funchal\'s signature, crowned by the record-breaking New Year — and the 20th century layered on Carnival parades, the Flower Festival and a calendar so dense the island now celebrates something every month. Which is exactly how we list them.', 'A festa é a mais antiga tecnologia social da Madeira. Numa terra de freguesias penduradas em arribas, o arraial — dia do santo, ação de graças da colheita e reunião da aldeia num só — era o momento de atravessar a serra para se estar junto: ruas atapetadas de flores e louro, vinho tirado do casco, espetada em pau de louro, o bailinho dançado até a vereda de regresso apanhar o nascer do sol. As romarias ao Monte, à Ponta Delgada e a Machico moviam milhares a pé muito antes de alguém chamar a isso caminhada. O comércio do vinho acrescentou pólvora — o fogo sobre a baía-anfiteatro virou assinatura do Funchal, coroada pela passagem de ano recordista — e o século XX somou o Carnaval, a Festa da Flor e um calendário tão denso que a ilha celebra algo todos os meses. É exatamente assim que os listamos.'),
  ]),
  Story('🍽', '1450 – today', 'The island kitchen', 'A cozinha da ilha', [
    Chapter('', '', '', '2012-bolo-do-caco.jpg', 'A baker in the traditional carapuça cap turns bolo do caco rounds on the hot plate of a bamboo festa stall — the sweet-potato flatbread was originally baked on a shard (caco) of basalt. Photo: Stephen Colebourne, CC BY 2.0.', 'Um padeiro de carapuça vira bolos do caco na chapa de uma banca de festa em bambu — o pão de batata-doce cozia-se originalmente sobre um caco de basalto. Foto: Stephen Colebourne, CC BY 2.0.', 'Madeira\'s food was invented by people who worked slopes all day: dense, portable, cooked over fire. Espetada — beef on a fresh laurel branch over embers — is arraial food; so is bolo do caco with garlic butter, baked where a stone gets hot. Milho frito (fried cornmeal cubes) fuelled field days, lapas (grilled limpets) fed the coast, and the black-scabbard fish came up from a kilometre down on hand lines. The oldest sweet on the table, bolo de mel, is made with sugar-cane molasses — a direct descendant of the engenhos, still kneaded for Christmas and traditionally broken by fist, never cut. Wash it down the historic way: wine from the terraces or a poncha beaten with the caralhinho — both have their own stories above.', 'A comida da Madeira foi inventada por gente que trabalhava encostas o dia inteiro: densa, portátil, feita ao lume. A espetada — vaca em pau de louro sobre brasas — é comida de arraial; o bolo do caco com manteiga de alho também, cozido onde uma pedra aquece. O milho frito alimentava os dias de fazenda, as lapas grelhadas a costa, e o peixe-espada preto subia de um quilómetro de fundo em linhas de mão. O doce mais antigo da mesa, o bolo de mel, faz-se com mel de cana — descendente direto dos engenhos, ainda amassado pelo Natal e partido à mão, nunca à faca. Para acompanhar, o vinho dos socalcos ou uma poncha batida com o caralhinho — ambos têm as suas histórias mais acima.'),
  ]),
  Story('🍷', '1425 – today', 'Drinks — wine, rum & poncha', 'Bebidas — vinho, rum e poncha', [
    Chapter('1600s – today', 'Madeira — the immortal wine', 'Madeira — o vinho imortal', '1900-borracheiros-cossart.jpg', 'A file of borracheiros under the vine pergola at Cossart Gordon & Co. — each man with a full goatskin of young wine on his shoulders and a walking staff, the lodge\'s great casks waiting on the right. Tinted postcard, c. 1900. Public domain.', 'Fila de borracheiros sob a latada nos armazéns da Cossart Gordon & Co. — cada homem com um borracho cheio de vinho ao ombro e o seu bordão, os cascos grandes à espera, à direita. Postal colorido, c. 1900. Domínio público.', 'Madeira wine was made immortal by accident. Casks shipped through the tropics arrived tasting better — cooked and rocked for months — and merchants began sending wine on round trips just to age it (vinho da roda). Ashore, the voyage was recreated with sun-warmed lofts (canteiro) and heated stores (estufa). The result barely dies: 18th-century bottles are opened and drunk today. It was the toast of the American Declaration of Independence in 1776, Shakespeare had a duke drown in a butt of its malmsey, and Napoleon\'s ship picked up a cask on the way to exile. Not bad for grapes grown on cliff terraces you can still run past above Câmara de Lobos.', 'O vinho Madeira tornou-se imortal por acidente. Os cascos que atravessavam os trópicos chegavam melhores — cozidos e embalados meses a fio — e os mercadores passaram a mandá-lo dar a volta só para envelhecer (o vinho da roda). Em terra, a viagem recriou-se com o canteiro ao sol e a estufa. O resultado quase não morre: ainda hoje se abrem garrafas do séc. XVIII. Foi o brinde da Independência americana em 1776, Shakespeare afogou um duque num tonel de malvasia, e o navio de Napoleão levou um casco a caminho do exílio. Nada mau para uvas de socalcos suspensos que ainda hoje se correm, acima de Câmara de Lobos.'),
    Chapter('1425 – today', 'Sugar, rum & poncha', 'Açúcar, rum e poncha', '1960-torreao-sugar-factory.jpg', 'The brick chimney of the Torreão (Hinton) sugar factory towering over Funchal\'s rooftops like a lighthouse of industry, c. 1960 — cane was still being milled in the middle of the city within living memory. ABM. Public domain.', 'A chaminé de tijolo da fábrica do Torreão (Hinton) por cima dos telhados do Funchal, c. 1960 — ainda se moía cana no meio da cidade em memória viva. ABM. Domínio público.', 'Sugar built Madeira twice. The first boom sweetened Renaissance Europe; the second, in the 1800s, turned cane juice into something better: aguardente de cana — Madeiran rum, distilled where the cane grows. The Hinton factory\'s chimney ruled Funchal\'s skyline until the 1980s, and in Porto da Cruz the steam-driven Engenho do Norte still fires up every spring harvest, one of Europe\'s last working steam distilleries. And the fisherman\'s dose of it became the island\'s password: poncha — rum, honey and lemon beaten with the wooden caralhinho in the taverns of Câmara de Lobos, drunk “to kill the germs” before the boats went out. Order one after a levada and you are drinking five centuries of cane in a glass.', 'O açúcar construiu a Madeira duas vezes. O primeiro ciclo adoçou a Europa do Renascimento; o segundo, no séc. XIX, transformou o sumo da cana em algo melhor: a aguardente de cana, destilada onde a cana cresce. A chaminé da fábrica Hinton mandou no céu do Funchal até aos anos 1980, e no Porto da Cruz o Engenho do Norte, a vapor, ainda acorda a cada apanha — uma das últimas destilarias a vapor da Europa. E a dose do pescador virou senha da ilha: a poncha — aguardente, mel e limão batidos com o caralhinho nas tascas de Câmara de Lobos, bebida «para matar o bicho» antes de os barcos saírem. Peça uma depois de uma levada e está a beber cinco séculos de cana num copo.'),
  ]),
];